name: todolist_app
description: A modern todo list application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1+1
  flutter_slidable: ^3.1.0
  google_fonts: ^4.0.4
  intl: ^0.19.0
  provider: ^6.0.0
  shared_preferences: ^2.0.8
  uuid: ^3.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
